### PR TITLE
Add setlocal/endlocal and cd to the batch file's directory.

### PR DESCRIPTION
**Pull request by XhmikosR**

### CODE REVIEW

**Comment by DeadManWalkingTO** [comment]
Why we need?

**Comment by XhmikosR** [comment]
Because without `setlocal`/`endlocal` all variables are global and can be read/modified by other scripts.

**Comment by XhmikosR** [comment]
Added one small change; this makes sure we are working in the same dir as the batch file.

BTW, perhaps we should output in `%TEMP%`.

**Comment by DeadManWalkingTO** [comment]
OK.
Thank you!

**Pull request merged**
